# Generated by Django 4.0.5 on 2023-06-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_weddingname_alter_wedding_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Полное имя'),
        ),
    ]
